theme: jekyll-theme-modernist
title: Froggum Icon Editor
description: Pixel perfect icons
url: https://sapoturge.github.io/froggum
icon: https://raw.githubusercontent.com/sapoturge/froggum/master/data/icons/48/com.github.sapoturge.froggum.svg
